# Generated by Django 5.1.6 on 2025-02-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_create_at_order_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
