# Generated by Django 5.1.6 on 2025-02-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_create_at_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
    ]
