
payroll_generate = """
    SELECT
        A.id
    FROM
        payroll_employee A
    WHERE
        {0}
    LIMIT {1} OFFSET {2}
"""

payroll_fetch_employees = """
    SELECT
        A.id as employee_id,
        A.badge_no as employee_badge_no,
        A.first_name as employee_first_name,
        A.middle_name as employee_middle_name,
        A.last_name as employee_last_name,
        A.suffix as employee_suffix,
        A.professional_extensions as employee_professional_extensions,

        B.is_flexi,
        B.is_manual_scheduled,
        B.is_manual_attendance,

        C.hourly_rate,
        C.daily_work_hours,
        C.is_require_attendance_approval,
        C.is_monthly_salary,
        C.monthly_rate,
        C.factor_rate
    FROM
        payroll_employee A
    JOIN
        payroll_schedule B ON B.employee_id_id = A.id
    JOIN
        payroll_employeecontract C ON C.employee_id_id = A.id
    WHERE
        A.id IN {}
"""

payroll_fetch_allowances = """
    SELECT
        A.employee_id_id as employee_id,
        A.id,
        A.name,
        A.amount,
        A.date_from,
        A.date_to,

        B.name as category_name,
        B.id as category_id,
        B.is_pro_rated,
        B.is_de_minimis,
        B.max_untaxable_amount
    FROM 
        payroll_allowance A
    LEFT JOIN
        payroll_allowancecategory B ON B.id = A.category_id_id
    WHERE
        A.is_active = True AND A.employee_id_id IN {}
"""

payroll_fetch_deductions = """
    SELECT
        A.employee_id_id as employee_id,
        A.force_max_employee_contribution,
        A.force_max_employer_contribution,
        B.id as deduction_id,
        B.name, 
        B.is_mandatory,
        B.basis_of_deduction,
        B.max_employee_value,
        B.max_employer_value
    FROM 
        payroll_deductionemployeerel A
    LEFT JOIN
        payroll_deduction B ON B.id = A.deduction_id_id
    WHERE
        B.is_active = True AND A.employee_id_id IN {}
"""

payroll_fetch_leaves = """
    SELECT
        A.employee_id_id as employee_id,
        A.date,
        A.duration,
        A.approval_status,
        A.leave_credit_id,

        C.id as leave_type_id,
        C.name,
        C.is_paid,
        C.is_reset,
        C.is_convertible,
        c.convert_rate_percent,
        C.accumulate_precision,
        C.convert_precision,
        C.is_applied_straight
    FROM
        payroll_leaveapplications A
    LEFT JOIN
        payroll_leavecredits B ON B.id = A.leave_credit_id
    LEFT JOIN
        payroll_leavetype C ON C.id = B.leave_type_id_id
    WHERE
        A.approval_status = 'APPROVED' AND A.date >= '{}' AND A.date <= '{}' AND A.employee_id_id IN {}
"""

payroll_fetch_shifts = """
    SELECT
        A.datetime_from,
        A.datetime_to,
        A.is_autogenerated,
        A.offset_from,
        A.offset_to,
        A.offset_approval_status,
        A.employee_id_id as employee_id
    FROM 
        payroll_employeeshifts A
    WHERE
        A.datetime_from >= '{}' AND A.datetime_to <= '{}' AND A.employee_id_id IN {}
"""

payroll_fetch_attendances = """
    SELECT
        A.id,
        A.time_in,
        A.time_out,
        A.attendance_approval_status,
        A.correct_time_in,
        A.correct_time_out,
        A.correction_approval_status,
        A.ot_from,
        A.ot_to,
        A.ot_approval_status,
        A.is_payroll_released,
        A.employee_id_id as employee_id,

        A.timein_source_id_id,
        B.name,

        A.manual_ot_duration,
        A.manual_tardiness_duration,
        A.manual_undertime_duration,
        A.manual_duration,
        A.manual_night_shift_ot,
        A.manual_leave_applied,
        A.manual_is_absent,
        A.manual_is_rest_day_ot,
        A.manual_attendance_type
    FROM
        payroll_attendance A
    LEFT JOIN
        payroll_timeinsource B ON B.id = A.timein_source_id_id
    WHERE
        A.time_in >= '{}' AND A.time_in <= '{}' AND A.employee_id_id IN {}
        AND A.is_active = True
"""

payroll_fetch_duplicate_attendances = """
    SELECT
        A.attendance_id
    FROM
        payroll_releasesaccumulatedattendances A
    JOIN
        payroll_attendance B ON A.attendance_id = B.id
    WHERE
        {} B.time_in >= '{}' AND B.time_in <= '{}' AND A.attendance_id IS NOT null
"""

payroll_fetch_config = """
    SELECT
        *
    FROM
        payroll_config A
    WHERE
        A.company_id = {}
"""

payroll_fetch_taxes = """
    SELECT
        *
    FROM
        payroll_tax A
    WHERE
        A.is_active = True and A.payroll_schedule = '{}'
"""

payroll_fetch_holidays = """
    SELECT
        *
    FROM
        payroll_holidays A
    WHERE
        A.company_id is null OR A.company_id = {}
"""

payroll_fiscal_year = """
    SELECT
        *
    FROM
        payroll_fiscalyear A
    WHERE
        A.is_active = True AND A.company_id = {}
"""

payroll_fetch_fiscal_year_lines = """
    SELECT
        *
    FROM
        payroll_fiscalyearlines A
    WHERE
        A.fiscal_year_id = {}
"""

payroll_fetch_deductions_on_fiscal_year_lines = """
    SELECT
        B.employee_id as employee_id,
        C.employer_share,
        C.employee_share,
        C.deductions_id,
        C.is_already_deducted
    FROM 
        payroll_releases A
    JOIN 
        payroll_releasesemployeetotals B ON A.id = B.releases_id
    LEFT JOIN
        payroll_releasesaccumulateddeductions C ON B.id = C.releases_employee_id
    LEFT JOIN 
        payroll_fiscalyearlines D ON A.fiscal_year_line_id = D.id
    WHERE
        A.fiscal_year_id = {0} AND (D.month = '{1}' AND D.fiscal_year_id = {0}) 
        AND B.employee_id IN {2}
"""

payroll_fetch_salaries_on_fiscal_year_lines = """
    SELECT
        B.employee_id as employee_id,
        B.basic_gross
    FROM 
        payroll_releases A
    JOIN 
        payroll_releasesemployeetotals B ON A.id = B.releases_id
    LEFT JOIN 
        payroll_fiscalyearlines C ON A.fiscal_year_line_id = C.id
    WHERE
        A.fiscal_year_id = {0} AND (C.month = '{1}' AND C.fiscal_year_id = {0}) 
        AND B.employee_id IN {2}
"""


fetch_other_deductions = """
    SELECT
        A.id,
        A.name,
        A.total_amount,
        A.amount_per_month,
        A.no_of_months,
        A.date_from,
        A.date_to,
        A.deduction_category_id,
        C.name as deduction_category_name,
        A.employee_id_id as employee_id,
        B.long_name
    FROM
        payroll_otherdeductions A
    JOIN
        payroll_employee B ON A.employee_id_id = B.id
    JOIN 
        payroll_deductioncategory C ON A.deduction_category_id = C.id
    WHERE
        A.is_active = True AND A.employee_id_id IN {0} AND
        date_from <= '{1}' AND date_to >= '{1}'
"""


payroll_fetch_de_minimis = """
    SELECT 
        *
    FROM 
        payroll_allowancecategory A
    WHERE
        A.company_id = 0 AND A.is_de_minimis = True
"""

payroll_fetch_accumulated_allowances = """
    SELECT
        B.fiscal_year_id,
        A.employee_id,
        C.daily_gross,
        C.employee_allowance_id_id as allowance_id,
        E.id as category_id,
        E.is_de_minimis
    FROM
        payroll_releasesemployeetotals A
    JOIN
        payroll_releases B ON B.id = A.releases_id
    LEFT JOIN
        payroll_releasesaccumulatedallowance C ON A.id = C.releases_employee_id
    JOIN
        payroll_allowance D ON C.employee_allowance_id_id = D.id
    JOIN 
        payroll_allowancecategory E ON D.category_id_id = E.id
    WHERE 
        A.employee_id IN {} AND B.fiscal_year_id = {} AND 
        B.is_active = True AND B.approval_status = 'APPROVED'
"""

payroll_fetch_deduction_matrix = """
    SELECT
        A.id as deduction_id,
        A.name, 
        A.is_mandatory,
        B.salary_from,
        B.salary_to,
        B.employee_max_contrib,
        B.employer_max_contrib,
        B.employee_percent_amount,
        B.employer_percent_amount,
        B.employee_fixed_amount,
        B.employer_fixed_amount
    FROM 
        payroll_deduction A 
    LEFT JOIN
        payroll_deductionmatrix B ON A.id = B.deduction_id_id
    WHERE
        (A.company_id = {} OR A.company_id is Null) AND A.is_active = True
"""

# SELECT QUERIES
select_releases_list = """
    SELECT
        id,
        date,
        cutoff_date_from,
        cutoff_date_to,
        approval_status,
        payroll_cycle
    FROM
        payroll_releases A
    WHERE
        {0}
    ORDER BY date DESC
    LIMIT {1} OFFSET {2}
"""

select_releases_one = """
    SELECT
        A.id as release_id,
        A.date,
        A.cutoff_date_from,
        A.cutoff_date_to,
        A.approval_status,
        A.payroll_cycle,
        A.produce_basic_deductions,
        A.produce_gross_deductions,
        A.is_generated,
        A.approval_status,
        C.id as fiscal_year_line_id,
        C.month as fiscal_year_line_name,
        A.fiscal_year_id,
        D.fiscal_year_name,
        B.*
    FROM
        payroll_releases A
    LEFT JOIN
        payroll_releasestotals B ON A.id = B.releases_id
    JOIN 
        payroll_fiscalyearlines C ON C.id = A.fiscal_year_line_id
    JOIN 
        payroll_fiscalyear D ON D.id = A.fiscal_year_id
    WHERE
        A.id = {}
"""

select_own_payroll_list = """
    SELECT
        B.id,
        A.date,
        A.cutoff_date_from,
        A.cutoff_date_to,
        A.approval_status,
        A.payroll_cycle
    FROM
        payroll_releases A 
    LEFT JOIN
        payroll_releasesemployeetotals B ON B.releases_id = A.id
    WHERE
        {0} AND B.employee_id = {3}
    LIMIT {1} OFFSET {2}
"""

select_other_income = """
    SELECT
        B.id,
        B.amount,
        B.employee_id,
        D.long_name as employee_long_name,
        B.other_income_type_id,
        C.name as other_income_type_name
    FROM 
        payroll_releases A
    JOIN 
        payroll_otherincome B ON B.releases_id = A.id
    JOIN 
        payroll_otherincometype C ON C.id = B.other_income_type_id
    JOIN
        payroll_employee D ON D.id = B.employee_id
    WHERE
        A.id = {}
"""

select_other_benefits = """
    SELECT
        B.id,
        B.amount,
        B.untaxable_threshold,
        B.employee_id,
        D.long_name as employee_long_name,
        B.other_benefit_type_id,
        C.name as other_benefit_type_name
    FROM 
        payroll_releases A
    JOIN 
        payroll_otherbenefits B ON B.releases_id = A.id
    JOIN 
        payroll_otherbenefitstype C ON C.id = B.other_benefit_type_id
    JOIN
        payroll_employee D ON D.id = B.employee_id
    WHERE
        A.id = {}
"""

select_earning_adjustments = """
    SELECT 
        B.id,
        B.amount,
        B.adjustment_remarks,
        B.employee_id,
        C.long_name as employee_long_name
    FROM 
        payroll_releases A
    JOIN 
        payroll_earningadjustments B ON A.id = B.releases_id
    JOIN 
        payroll_employee C ON C.id = B.employee_id
    WHERE 
        A.id = {}
"""

select_payroll_employee_list = """
    SELECT
        A.id,
        A.date,
        A.cutoff_date_from,
        A.cutoff_date_to,
        A.approval_status,
        A.payroll_cycle,
        B.*,
        C.first_name,
        C.middle_name,
        C.last_name,
        C.suffix,
        C.badge_no,
        C.professional_extensions
    FROM
        payroll_releases A
    JOIN
        payroll_releasesemployeetotals B ON A.id = B.releases_id
    JOIN
        payroll_employee C ON B.employee_id = C.id
    WHERE
        {0}
    LIMIT {1} OFFSET {2}
"""

select_payroll_employee_one = """
    SELECT
        A.*,
        B.first_name,
        B.middle_name,
        B.last_name,
        B.suffix,
        B.professional_extensions,
        B.badge_no,
        
        D.name as department_name,
        E.name as position_name,
        
        F.date as release_date,
        F.cutoff_date_from,
        F.cutoff_date_to,
        F.payroll_cycle
    FROM
        payroll_releasesemployeetotals A
    JOIN
        payroll_employee B ON A.employee_id = B.id
    JOIN 
        payroll_employeecontract C ON C.employee_id_id = B.id
    LEFT JOIN
        payroll_department D ON D.id = C.department_id
    LEFT JOIN 
        payroll_employeepositions E ON E.id = C.employee_positions_id
    JOIN
        payroll_releases F ON F.id = A.releases_id
    WHERE
        A.id = {}
"""

select_payroll_employee_attendances_one = """
    SELECT
        A.*,
        B.time_in,
        B.time_out,
        B.attendance_approval_status,
        B.correct_time_in,
        B.correct_time_out,
        B.correction_approval_status,
        B.ot_from,
        B.ot_to,
        B.ot_approval_status
    FROM
        payroll_releasesaccumulatedattendances A
    LEFT JOIN
        payroll_attendance B ON B.id = A.attendance_id
    WHERE
        A.releases_employee_id = {}
"""

select_payroll_employee_allowances_one = """
    SELECT
        A.daily_gross,
        B.name
    FROM
        payroll_releasesaccumulatedallowance A
    LEFT JOIN
        payroll_allowance B ON B.id = A.employee_allowance_id_id
    WHERE
        A.releases_employee_id = {}
"""

select_payroll_employee_deductions_one = """
    SELECT
        A.*,
        B.name,
        B.basis_of_deduction,
        B.is_mandatory
    FROM
        payroll_releasesaccumulateddeductions A
    LEFT JOIN
        payroll_deduction B ON A.deductions_id = B.id
    WHERE
        A.releases_employee_id = {}
"""

insert_payroll_totals = """
    INSERT INTO
        payroll_releasestotals
    (
        releases_id,
        
        undertime_gross,
        tardiness_gross,
        absent_gross,
        paid_leave_gross,
        unpaid_leave_gross,
        
        other_income,
        other_benefits,
        earnings_adjustment,
        other_deductions,
        
        ordinary_gross,
        ordinary_holiday_gross,
        ordinary_overtime_gross,
        night_diff_gross,
        night_diff_ot_gross,
        
        rest_day_gross,
        rest_day_overtime_gross,
        rest_day_night_diff_gross,
        rest_day_night_diff_ot_gross,
        
        regular_holiday,
        special_holiday,
        double_regular_holiday,
        double_special_holiday,
        
        night_regular_holiday,
        night_special_holiday,
        night_double_regular_holiday,
        night_double_special_holiday,
        
        ot_regular_holiday,
        ot_special_holiday,
        ot_double_regular_holiday,
        ot_double_special_holiday,
        
        ot_night_regular_holiday,
        ot_night_special_holiday,
        ot_night_double_regular_holiday,
        ot_night_double_special_holiday,
        
        rest_day_regular_holiday,
        rest_day_special_holiday,
        rest_day_double_regular_holiday,
        rest_day_double_special_holiday,
        
        rest_day_night_regular_holiday,
        rest_day_night_special_holiday,
        rest_day_night_double_regular_holiday,
        rest_day_night_double_special_holiday,
        
        rest_day_ot_regular_holiday,
        rest_day_ot_special_holiday,
        rest_day_ot_double_regular_holiday,
        rest_day_ot_double_special_holiday,
        
        rest_day_ot_night_regular_holiday,
        rest_day_ot_night_special_holiday,
        rest_day_ot_night_double_regular_holiday,
        rest_day_ot_night_double_special_holiday,
        
        basic_gross,
        earnings_total,
        deducted_gross,
        deductions_total,
        allowance_gross,
        taxable_allowance,
        deducted_employee_gross,
        deducted_employer_gross,
        salary_gross,
        taxes_total,
        net_total
        
    ) VALUES
    {}
"""


insert_payroll_employee = """
    INSERT INTO
        payroll_releasesemployeetotals
    (
        employee_id,
        releases_id,
        
        hourly_rate,
        daily_rate,
        monthly_rate,
        
        undertime_hrs,
        tardiness_hrs,
        absent_hrs,
        paid_leave_hrs,
        unpaid_leave_hrs,
        
        ordinary_hrs,
        ordinary_holiday_hrs,
        ordinary_overtime_hrs,
        night_diff_hrs,
        night_diff_ot_hrs,
        
        rest_day_hrs,
        rest_day_overtime_hrs, 
        rest_day_night_diff_hrs,
        rest_day_night_diff_ot_hrs,

        regular_holiday_hrs,
        special_holiday_hrs,
        double_regular_holiday_hrs,
        double_special_holiday_hrs,
        
        night_regular_holiday_hrs,
        night_special_holiday_hrs,
        night_double_regular_holiday_hrs,
        night_double_special_holiday_hrs,
        
        ot_regular_holiday_hrs,
        ot_special_holiday_hrs,
        ot_double_regular_holiday_hrs,
        ot_double_special_holiday_hrs,
        
        ot_night_regular_holiday_hrs,
        ot_night_special_holiday_hrs,
        ot_night_double_regular_holiday_hrs,
        ot_night_double_special_holiday_hrs,
        
        rest_day_regular_holiday_hrs,
        rest_day_special_holiday_hrs,
        rest_day_double_regular_holiday_hrs,
        rest_day_double_special_holiday_hrs,
        
        rest_day_night_regular_holiday_hrs,
        rest_day_night_special_holiday_hrs,
        rest_day_night_double_regular_holiday_hrs,
        rest_day_night_double_special_holiday_hrs,
        
        rest_day_ot_regular_holiday_hrs,
        rest_day_ot_special_holiday_hrs,
        rest_day_ot_double_regular_holiday_hrs,
        rest_day_ot_double_special_holiday_hrs,
        
        rest_day_ot_night_regular_holiday_hrs,
        rest_day_ot_night_special_holiday_hrs,
        rest_day_ot_night_double_regular_holiday_hrs,
        rest_day_ot_night_double_special_holiday_hrs,
        
        undertime_gross,
        tardiness_gross,
        absent_gross,
        paid_leave_gross,
        unpaid_leave_gross,
        
        other_income,
        other_benefits,
        earnings_adjustment,
        other_deductions,
        
        ordinary_gross,
        ordinary_holiday_gross,
        ordinary_overtime_gross,
        night_diff_gross,
        night_diff_ot_gross,
        
        rest_day_gross,
        rest_day_overtime_gross, 
        rest_day_night_diff_gross,
        rest_day_night_diff_ot_gross,
        
        regular_holiday,
        special_holiday,
        double_regular_holiday,
        double_special_holiday,
        
        night_regular_holiday,
        night_special_holiday,
        night_double_regular_holiday,
        night_double_special_holiday,
        
        ot_regular_holiday,
        ot_special_holiday,
        ot_double_regular_holiday,
        ot_double_special_holiday,
        
        ot_night_regular_holiday,
        ot_night_special_holiday,
        ot_night_double_regular_holiday,
        ot_night_double_special_holiday,
        
        rest_day_regular_holiday,
        rest_day_special_holiday,
        rest_day_double_regular_holiday,
        rest_day_double_special_holiday,
        
        rest_day_night_regular_holiday,
        rest_day_night_special_holiday,
        rest_day_night_double_regular_holiday,
        rest_day_night_double_special_holiday,
        
        rest_day_ot_regular_holiday,
        rest_day_ot_special_holiday,
        rest_day_ot_double_regular_holiday,
        rest_day_ot_double_special_holiday,
        
        rest_day_ot_night_regular_holiday,
        rest_day_ot_night_special_holiday,
        rest_day_ot_night_double_regular_holiday,
        rest_day_ot_night_double_special_holiday,
        
        basic_gross,
        earnings_total,
        deducted_gross,
        deductions_total,
        allowance_gross,
        taxable_allowance,
        deducted_employee_gross,
        deducted_employer_gross,
        salary_gross,
        taxes_total,
        net_total
    ) VALUES
    {}
    RETURNING id, employee_id
"""

insert_payroll_attendances = """
    INSERT INTO
        payroll_releasesaccumulatedattendances
    (
        releases_employee_id,
        attendance_id,
        
        total_absent_hrs,
        undertime_hrs,
        tardiness_hrs,
        total_paid_leave_hrs,
        total_unpaid_leave_hrs,
    
        total_ordinary_hrs,
        total_ordinary_ot_hrs,
        total_night_diff_hrs,
        total_ot_night_diff_hrs,
    
        total_rest_day_hrs, 
        total_rest_day_ot_hrs, 
        total_rest_day_night_diff_hrs,
        total_rest_day_ot_night_diff_hrs,
    
        total_regular_holiday_hrs,
        total_double_regular_holiday_hrs,
        total_special_holiday_hrs,
        total_double_special_holiday_hrs,
    
        total_night_regular_holiday_hrs,
        total_night_double_regular_holiday_hrs,
        total_night_special_holiday_hrs,
        total_night_double_special_holiday_hrs,
    
        total_ot_regular_holiday_hrs,
        total_ot_double_regular_holiday_hrs,
        total_ot_special_holiday_hrs,
        total_ot_double_special_holiday_hrs,
    
        total_night_ot_regular_holiday_hrs,
        total_night_ot_double_regular_holiday_hrs,
        total_night_ot_special_holiday_hrs,
        total_night_ot_double_special_holiday_hrs,
    
        rest_day_total_regular_holiday_hrs,
        rest_day_total_double_regular_holiday_hrs,
        rest_day_total_special_holiday_hrs,
        rest_day_total_double_special_holiday_hrs,
    
        rest_day_total_night_regular_holiday_hrs,
        rest_day_total_night_double_regular_holiday_hrs,
        rest_day_total_night_special_holiday_hrs,
        rest_day_total_night_double_special_holiday_hrs,
    
        rest_day_total_ot_regular_holiday_hrs,
        rest_day_total_ot_double_regular_holiday_hrs,
        rest_day_total_ot_special_holiday_hrs,
        rest_day_total_ot_double_special_holiday_hrs,
    
        rest_day_total_night_ot_regular_holiday_hrs,
        rest_day_total_night_ot_double_regular_holiday_hrs,
        rest_day_total_night_ot_special_holiday_hrs,
        rest_day_total_night_ot_double_special_holiday_hrs,
    
        tardiness,
        undertime,
        absent,
        paid_leave,
        unpaid_leave,
    
        ordinary,
        ordinary_ot,
        night_diff,
        night_diff_ot,
        
        rest_day,
        rest_day_ot, 
        rest_day_night_diff,
        rest_day_night_diff_ot,
        
        regular_holiday,
        double_regular_holiday,
        special_holiday,
        double_special_holiday,
    
        night_regular_holiday,
        night_double_regular_holiday,
        night_special_holiday,
        night_double_special_holiday,
    
        ot_regular_holiday,
        ot_double_regular_holiday,
        ot_special_holiday,
        ot_double_special_holiday,
    
        ot_night_regular_holiday,
        ot_night_double_regular_holiday,
        ot_night_special_holiday,
        ot_night_double_special_holiday,
        
        rest_day_regular_holiday,
        rest_day_double_regular_holiday,
        rest_day_special_holiday,
        rest_day_double_special_holiday,
    
        rest_day_night_regular_holiday,
        rest_day_night_double_regular_holiday,
        rest_day_night_special_holiday,
        rest_day_night_double_special_holiday,
    
        rest_day_ot_regular_holiday,
        rest_day_ot_double_regular_holiday,
        rest_day_ot_special_holiday,
        rest_day_ot_double_special_holiday,
    
        rest_day_ot_night_regular_holiday,
        rest_day_ot_night_double_regular_holiday,
        rest_day_ot_night_special_holiday,
        rest_day_ot_night_double_special_holiday
    ) VALUES
    {}
"""

insert_payroll_allowance = """
    INSERT INTO
        payroll_releasesaccumulatedallowance
    (
        daily_gross,
        employee_allowance_id_id,
        releases_employee_id
    ) VALUES
    {}
"""

insert_payroll_deductions = """
    INSERT INTO
        payroll_releasesaccumulateddeductions
    (
        deductions_id,
        releases_employee_id,
        employer_share,
        employee_share,
        is_already_deducted
    ) VALUES
    {}
"""

insert_payroll_other_deductions = """
    INSERT INTO
        payroll_releasesaccumulatedotherdeductions
    (
        other_deductions_id,
        releases_employee_id,
        amount
    ) VALUES
    {}
"""

select_payroll_employee_details_list = """
    SELECT
        A.id as release_id,
        A.date,
        A.cutoff_date_from,
        A.cutoff_date_to,
        A.approval_status,
        A.payroll_cycle,
        B.*,
        C.first_name,
        C.middle_name,
        C.last_name,
        C.suffix,
        C.badge_no,
        C.professional_extensions,
        
        E.name as department_name,
        F.name as position_name
    FROM
        payroll_releases A
    JOIN
        payroll_releasesemployeetotals B ON A.id = B.releases_id
    JOIN
        payroll_employee C ON B.employee_id = C.id
    JOIN 
        payroll_employeecontract D ON D.employee_id_id = C.id
    LEFT JOIN
        payroll_department E ON E.id = D.department_id
    LEFT JOIN 
        payroll_employeepositions F ON F.id = D.employee_positions_id
    WHERE
        A.id = {0}
"""


select_payroll_employee_deductions_list_for_pdf = """
    SELECT
        A.*,
        B.name,
        B.basis_of_deduction,
        B.is_mandatory
    FROM
        payroll_releasesaccumulateddeductions A
    LEFT JOIN
        payroll_deduction B ON A.deductions_id = B.id
    WHERE
        A.releases_employee_id IN ({})
"""

select_payroll_employee_allowances_list_for_pdf = """
    SELECT
        A.releases_employee_id,
        A.daily_gross,
        B.name
    FROM
        payroll_releasesaccumulatedallowance A
    LEFT JOIN
        payroll_allowance B ON B.id = A.employee_allowance_id_id
    WHERE
        A.releases_employee_id IN ({})
"""

select_payroll_releases_employee_ids = """
    SELECT
        A.id
    FROM
        payroll_releasesemployeetotals A
    WHERE
        A.releases_id = {}
"""